import { Produto } from '../model/produto';

// Preços em centavos: 1490 representa R$ 14,90.
export const CATEGORIES = ['Escrita', 'Cores & criação', 'Essenciais', 'Organização'];
export const PRODUCTS: Produto[] = [
  {
    id: 1,
    name: 'Marca-texto Lumi Color azul',
    brand: 'Pilot',
    category: 'Cores & criação',
    price: 1490,
    description:
      'Destaque suas ideias com um toque de azul. Marca-texto Pilot Lumi Color 200-SL para organizar leituras, resumos e anotações.',
    color: 'Azul',
    specifications: [
      { label: 'Modelo / linha', value: 'Lumi Color 200-SL' },
      { label: 'Conteúdo da embalagem', value: '1 marca-texto' },
      { label: 'Tipo de ponta', value: 'Chanfrada' },
      { label: 'Indicação na embalagem', value: 'Ponta 4,0 mm' },
      { label: 'Uso', value: 'Destaque de textos e anotações' },
      { label: 'Dimensões (altura × largura × profundidade)', value: 'Não informadas' },
    ],
  },
  {
    id: 2,
    name: 'Lápis grafite EcoLápis',
    brand: 'Faber-Castell',
    category: 'Escrita',
    price: 890,
    description:
      'Do primeiro rascunho à última anotação. Conjunto de lápis grafite para escrever e desenhar no dia a dia.',
    color: 'Grafite',
    specifications: [
      { label: 'Modelo / linha', value: 'Eco Grip 2001' },
      { label: 'Conteúdo da embalagem', value: '3 lápis grafite' },
      { label: 'Graduação', value: 'Nº 2 / HB' },
      { label: 'Corpo', value: 'Preto com pontos de apoio' },
      { label: 'Uso', value: 'Escrita e desenho a grafite' },
      { label: 'Dimensões (altura × largura × profundidade)', value: 'Não informadas' },
    ],
  },
  {
    id: 3,
    name: 'Canetas Cristal • 4 cores',
    brand: 'BIC',
    category: 'Escrita',
    price: 990,
    description:
      'O clássico do estojo em um conjunto de quatro cores. Para alternar entre anotações, títulos e detalhes.',
    color: 'Sortidas',
    specifications: [
      { label: 'Modelo / linha', value: 'Cristal' },
      { label: 'Conteúdo da embalagem', value: '4 canetas esferográficas' },
      { label: 'Cores da tinta', value: 'Azul, verde, vermelha e preta' },
      { label: 'Ponta', value: '1,0 mm, conforme embalagem' },
      { label: 'Fechamento', value: 'Tampa removível' },
      { label: 'Dimensões (altura × largura × profundidade)', value: 'Não informadas' },
    ],
  },
  {
    id: 4,
    name: 'Marca-texto amarelo',
    brand: 'BIC',
    category: 'Cores & criação',
    price: 690,
    description:
      'Dê destaque ao que importa. Um toque de amarelo para marcar trechos e encontrar suas ideias favoritas.',
    color: 'Amarelo',
    specifications: [
      { label: 'Modelo / linha', value: 'Marking' },
      { label: 'Conteúdo da embalagem', value: '1 marca-texto amarelo' },
      { label: 'Tipo de ponta', value: 'Chanfrada' },
      { label: 'Fechamento', value: 'Tampa removível' },
      { label: 'Uso', value: 'Destaque de textos' },
      { label: 'Dimensões (altura × largura × profundidade)', value: 'Não informadas' },
    ],
  },
  {
    id: 5,
    name: 'Marca-textos • 5 cores',
    brand: 'BIC',
    category: 'Cores & criação',
    price: 2490,
    description:
      'Uma paleta para organizar seus estudos por cor e deixar cada página com a sua cara.',
    color: 'Sortidas',
    specifications: [
      { label: 'Modelo / linha', value: 'Marking' },
      { label: 'Conteúdo da embalagem', value: '5 marca-textos' },
      { label: 'Cores da tinta', value: 'Amarela, verde, laranja, rosa e roxa' },
      { label: 'Tipo de ponta', value: 'Chanfrada' },
      { label: 'Fechamento', value: 'Tampas removíveis' },
      { label: 'Dimensões (altura × largura × profundidade)', value: 'Não informadas' },
    ],
  },
  {
    id: 6,
    name: 'Ecogiz de cera • 12 cores',
    brand: 'Faber-Castell',
    category: 'Cores & criação',
    price: 1990,
    description:
      'Doze cores para desenhar e criar. Caixa de ecogizes de cera Faber-Castell com um apontador, indicada na embalagem para mãozinhas pequenas.',
    color: 'Sortidas',
    specifications: [
      { label: 'Modelo / linha', value: 'Ecogiz de cera' },
      { label: 'Conteúdo da embalagem', value: '12 ecogizes de cera + 1 apontador (13 peças)' },
      { label: 'Cores', value: '12 cores sortidas' },
      { label: 'Tipo de material de desenho', value: 'Giz de cera' },
      { label: 'Formato', value: 'Corpo curto com ponta para desenhar' },
      { label: 'Dimensões (altura × largura × profundidade)', value: 'Não informadas' },
    ],
  },
  {
    id: 7,
    name: 'Borrachas coloridas • 2 un.',
    brand: 'Faber-Castell',
    category: 'Essenciais',
    price: 790,
    description:
      'Porque recomeçar faz parte de criar. Dupla de borrachas coloridas para acompanhar seus lápis.',
    color: 'Amarelo e rosa',
    specifications: [
      { label: 'Modelo / linha', value: 'Não identificado' },
      { label: 'Conteúdo da embalagem', value: '2 borrachas' },
      { label: 'Cores', value: 'Amarela e rosa' },
      { label: 'Formato', value: 'Retangular' },
      { label: 'Proteção', value: 'Capas individuais de apoio' },
      { label: 'Dimensões (altura × largura × profundidade)', value: 'Não informadas' },
    ],
  },
  {
    id: 8,
    name: 'Cola em bastão',
    brand: 'Faber-Castell',
    category: 'Essenciais',
    price: 850,
    description:
      'Para colagens, trabalhos e pequenas invenções. Cola em bastão prática para projetos com papel.',
    color: 'Embalagem vermelha',
    specifications: [
      { label: 'Modelo / linha', value: 'Cola em bastão' },
      { label: 'Conteúdo da embalagem', value: '1 bastão de cola' },
      { label: 'Peso líquido', value: '10 g' },
      { label: 'Características da embalagem', value: 'Atóxica e lavável' },
      { label: 'Aplicação', value: 'Colagens com papel' },
      { label: 'Dimensões (altura × largura × profundidade)', value: 'Não informadas' },
    ],
  },
  {
    id: 9,
    name: 'Tesoura escolar',
    brand: 'Maped',
    category: 'Essenciais',
    price: 1290,
    description:
      'Um essencial para recortes e atividades de papelaria. Use com cuidado e supervisão de um adulto quando necessário.',
    color: 'Preto',
    specifications: [
      { label: 'Modelo / linha', value: 'Essentials' },
      { label: 'Conteúdo da embalagem', value: '1 tesoura escolar' },
      { label: 'Comprimento', value: '13 cm (5 polegadas, conforme embalagem)' },
      { label: 'Formato da ponta', value: 'Arredondada' },
      { label: 'Cor do cabo', value: 'Preta' },
      { label: 'Cuidados', value: 'Utilizar com supervisão de um adulto quando necessário' },
      { label: 'Largura e espessura', value: 'Não informadas' },
    ],
  },
  {
    id: 10,
    name: 'Grampeador de mesa',
    brand: 'CIS',
    category: 'Organização',
    price: 2290,
    description:
      'Junte as páginas e coloque as ideias em ordem. Grampeador compacto para sua mesa de estudos ou trabalho.',
    color: 'Preto',
    specifications: [
      { label: 'Modelo / linha', value: 'Não identificado' },
      { label: 'Conteúdo do item', value: '1 grampeador de mesa' },
      { label: 'Cor', value: 'Preta' },
      { label: 'Formato', value: 'Base de apoio para mesa' },
      { label: 'Capacidade de folhas', value: 'Não informada' },
      { label: 'Tipo de grampo compatível', value: 'Não informado' },
      { label: 'Dimensões (altura × largura × profundidade)', value: 'Não informadas' },
    ],
  },
  {
    id: 11,
    name: 'Estojo azul',
    brand: 'Seleção Rabisco',
    category: 'Organização',
    price: 2990,
    description:
      'Um lugar para guardar seus materiais favoritos. Estojo com fechamento em zíper em um tom suave de azul.',
    color: 'Azul-claro',
    specifications: [
      { label: 'Modelo / linha', value: 'Não identificado' },
      { label: 'Conteúdo do item', value: '1 estojo' },
      { label: 'Fechamento', value: 'Zíper' },
      { label: 'Formato', value: 'Retangular' },
      { label: 'Material / composição', value: 'Não informado' },
      {
        label: 'Fabricante',
        value: 'Não identificado; Seleção Rabisco é a identificação do catálogo',
      },
      { label: 'Dimensões (altura × largura × profundidade)', value: 'Não informadas' },
    ],
  },
  {
    id: 12,
    name: 'Mochila preta',
    brand: 'JanSport',
    category: 'Organização',
    price: 24990,
    description:
      'Leve suas ideias com você. Mochila preta com compartimentos para organizar os materiais do dia a dia.',
    color: 'Preto',
    specifications: [
      { label: 'Modelo / linha', value: 'Não identificado' },
      { label: 'Conteúdo do item', value: '1 mochila' },
      { label: 'Fechamento', value: 'Zíper' },
      {
        label: 'Detalhes visíveis',
        value: 'Alça superior, bolsos frontais e bolso lateral em tela',
      },
      { label: 'Capacidade em litros', value: 'Não informada' },
      { label: 'Material / composição', value: 'Não informado' },
      { label: 'Acessório da foto', value: 'Garrafa ilustrativa; inclusão não confirmada' },
      { label: 'Dimensões (altura × largura × profundidade)', value: 'Não informadas' },
    ],
  },
];
